# Generated by Django 5.1.5 on 2025-01-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='task_manager_task',
        ),
    ]
